### ISSUE TITLE
Split project options out into separate file

### ISSUE THREAD

**Issue by ZedThree** [Fortran-FOSS-Programmers/ford#449]
See #448 for one motivation (separate encoding for options file and index page).

Another motivation is that the markdown metadata processing extension is a bit awkward, and using a proper config file format would make both parsing and writing the options a bit easier (for example, lists are currently a pain to write).

**Comment by awvwgk** [comment]
Maybe FORD could leverage the fpm package manifest using the free table *extra*:

```toml
[extra.ford]
project = "Example Project"
src_dir = ["./src"]
output_dir = ["./doc"]
project_github = "https://github.com/cmacmackin/futility"
project_website = "https://github.com/"
summary = "Some Fortran program which I wrote."
author = "John Doe"
author_description = "I program stuff in Fortran."
github = "https://github.com/cmacmackin"
email = "john.doe@example.com"
fpp_extensions = ["fpp"]
preprocess = true
macro = ["HAS_DECREMENT"]
predocmark = ">"
docmark_alt = "#"
predocmark_alt = "<"
display = ["public", "protected"]
source = false
graph= true
search = true
extra_mods.json_module = "http://jacobwilliams.github.io/json-fortran/"
extra_mods.futility = "http://cmacmackin.github.io/"
extra_mods.iso_fortran_env = "https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fFORTRAN_005fENV.html"
license = "by-nc"
extra_filetypes = "sh"
max_frontpage_items = 4
exclude = ["excluded_file.f90"]
exclude_dir = ["src/excluded_directory"]
```

With a library like *tomli*, *tomlkit* or *pytomlpp* it should be straight-forward to read as well if you are okay with an additional dependency:

```python
from pathlib import Path
# Choose any available TOML library in Python (alternatively decide for one)
for impl in ["tomllib", "tomli", "tomlkit", "pytomlpp"]:
    try:
        tomllib = __import__(impl)
        break
    except ModuleNotFoundError:
        tomllib = None

with open(Path("fpm.toml"), "rb") as fd:
    data = tomllib.load(fd)

ford_data = data.get("extra", {}).get("ford")
```

There is also [*fpm.metadata*](https://github.com/fortran-lang/fpm-metadata) which allows to directly load the complete manifest:

```python
from pathlib import Path
from fpm.metadata import load_manifest

manifest = load_manifest(Path("fpm.toml"))
ford_data = manifest.extra.get("ford")
```
