### ISSUE TITLE
How to defined index page content with extra.ford usage

### ISSUE THREAD

**Issue by jacobwilliams** [Fortran-FOSS-Programmers/ford#695]
When using `extra.ford` in `fpm.toml` where/how do I define the contents of the main index page for the docs? What seems to be happening is that it's including the `fpm.toml` contents there, which isn't what I want. Normally I just want it to be the project README.md file, which I have done with the `ford.md` way by using `{!README.md!}`.

**Comment by ZedThree** [comment]
The difference between using `ford.md` and `fpm.toml` _should_ literally just be moving the config into `fpm.toml` (and into the correct form). So here's the [example project](https://github.com/Fortran-FOSS-Programmers/ford/blob/master/example/example-project-file.md) included in ford:

`example-project-file.md`:
```markdown
Hi, my name is ${USER}.

This is a project which I wrote. This file will provide the documents. I'm
writing the body of the text here. It contains an overall description of the
project. It might explain how to go about installing/compiling it. It might
provide a change-log for the code. [[linalg]] Maybe it will talk about the
history and/or motivation for this software.

...
```

`fpm.toml`:
```toml
[extra.ford]
project = "Example Project"
src_dir = "./src"
output_dir = "./doc"
project_github = "https://github.com/cmacmackin/futility"
project_website = "https://github.com"
summary = "Some Fortran program which I wrote."
author = "John Doe"
author_description = "I program stuff in Fortran."
github = "https://github.com/cmacmackin"
email = "john.doe@example.com"
fpp_extensions = "fpp"
preprocess = "true"
macro = "HAS_DECREMENT"
predocmark = ">"
docmark_alt = "#"
predocmark_alt = "<"
display = ["public", "protected"]
source = false
graph = true
search = true
license = "by-nc"
extra_filetypes = [{extension = "sh", comment="#"}]
max_frontpage_items = "4"
exclude = "src/excluded_file.f90"
exclude_dir = "src/excluded_directory"
page_dir = "pages"

[extra.ford.extra_mods]
json_module = "http://jacobwilliams.github.io/json-fortran/"
futility = "http://cmacmackin.github.io"
iso_fortran_env = "https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fFORTRAN_005fENV.html"
```

and run with `ford example-project-file.md`. This produces identical output to the original version.

If that's not working for you, then it's a bug!

Ah, writing this out, maybe you're running `ford fpm.toml` rather than `ford ford.md`? Looking at the docs, it's not clear at all that the latter is still correct, and `fpm.toml` is automatically picked up. That's a bug in the docs, and I'll fix that now!
